"""Robustness check 5 — report DISTRIBUTION of CAGR/Sharpe within each family.

The headline sweeps always report the max. The median and 25th percentile
matter more: they describe what a random pick within that family would
deliver. A family whose best is 30% CAGR but whose median is 5% is a pure
overfit lottery.

Reads letf_is_oos_all.csv (generated by letf_is_oos.py).
"""
from pathlib import Path
import numpy as np
import pandas as pd

OUT = Path("/home/user/bonds/data/results")


def dist_row(label, s):
    return {
        "family": label, "n": len(s),
        "min": s.min(), "p10": s.quantile(.10), "p25": s.quantile(.25),
        "p50": s.median(), "p75": s.quantile(.75), "p90": s.quantile(.90),
        "max": s.max(), "mean": s.mean(), "std": s.std(),
    }


def main():
    df = pd.read_csv(OUT / "letf_is_oos_all.csv")
    print(f"Loaded {len(df)} configs from letf_is_oos_all.csv")

    for metric, label in [("is_sharpe","IS Sharpe"),
                          ("oos_sharpe","OOS Sharpe"),
                          ("is_cagr","IS CAGR%"),
                          ("oos_cagr","OOS CAGR%"),
                          ("is_mdd","IS MDD%"),
                          ("oos_mdd","OOS MDD%")]:
        print(f"\n=== Distribution of {label} by family ===")
        rows = []
        for fam in sorted(df["family"].unique()):
            sub = df[df.family == fam][metric]
            rows.append(dist_row(fam, sub))
        d = pd.DataFrame(rows)
        print(d.to_string(index=False, float_format=lambda x: f"{x:>6.2f}"))

    # NEW: agreement between IS-rank and OOS-rank
    print("\n=== IS/OOS rank stability (Spearman corr of Sharpe) ===")
    for fam in sorted(df["family"].unique()):
        sub = df[df.family == fam]
        if len(sub) < 3: continue
        corr = sub[["is_sharpe","oos_sharpe"]].corr(method="spearman").iloc[0,1]
        # top-quartile IS: what share stays top-quartile OOS?
        is_q = sub["is_sharpe"].quantile(.75)
        oos_q = sub["oos_sharpe"].quantile(.75)
        top_is = sub[sub["is_sharpe"] >= is_q]
        persist = (top_is["oos_sharpe"] >= oos_q).mean()
        print(f"  {fam:<15s}  n={len(sub):>3d}  "
              f"Spearman SR(IS,OOS)={corr:+.2f}  "
              f"top-Q persistence={persist:.0%}")

    # Save summary table
    agg = (df.groupby("family")
             .agg(n=("label","count"),
                  is_sr_med=("is_sharpe","median"),
                  is_sr_max=("is_sharpe","max"),
                  oos_sr_med=("oos_sharpe","median"),
                  oos_sr_max=("oos_sharpe","max"),
                  is_cagr_med=("is_cagr","median"),
                  oos_cagr_med=("oos_cagr","median"),
                  oos_mdd_med=("oos_mdd","median"))
             .round(2))
    agg.to_csv(OUT / "letf_family_dist.csv")
    print("\n=== Family summary ===")
    print(agg.to_string())


if __name__ == "__main__":
    main()
