"""PHOENIX v4 — canonical production strategy.

7-sleeve superset, equal-weight-active allocator, tail overlay. All sleeve return
series follow the unified realization-dated booking convention
(alt/sleeve_engine.py): the value at date t is the P&L realized over
open[t-1] -> open[t] by a position decided from information through
close[t-2]. Same-date rows are therefore contemporaneous across sleeves and
the blend NAV is an executable portfolio's NAV.

Sleeves (each generated by its own module into data/results/*.csv):
    VAN  vanguard_strategy.py    monthly LETF rotation + macro-gate participation
    ORI  orion_strategy.py       weekly top-K momentum, risk+safe books
    HEL  helios_strategy.py      weekly underlying-trend via LETFs (signals lagged)
    CRY  phoenix_v2_crypto.py    weekly TSMOM on spot-chained BTC/ETH -> IBIT/ETHA
    REV  reversal_strategy.py    5d dip-buying inside uptrends via LETFs
    TOM  tom_strategy.py         turn-of-month TQQQ seasonality
    BND  bondtrend_strategy.py   long/flat duration trend via TMF
(QUANTUM was retired: its published 2010-2018 history was in-sample model
output; rebuilt walk-forward it shows no robust edge — Sharpe 0.2-0.6
across horizons with -77% MDD. See PHOENIX_V3.md.)

Allocator (v4: equal weight over active sleeves — no estimation at all):
    W_i(t) = 1 / n_active(t) for every sleeve whose activation date has
    passed. Activation dates are fixed ex ante: every sleeve at the blend
    start, except CRY which activates at IBIT's listing (2024-01-11) — the
    first date a US-brokerage ETF investor could actually hold spot crypto
    (see "Investability" below). No trailing statistics are consumed, so
    there is nothing to overfit, no year-boundary refit edge case, and live
    weights are trivially identical to backtest weights.

    Why not the v3 walk-forward allocator (kept below as ALLOCATOR =
    "walk_forward")? Independent re-review found it dominated by 1/N on
    every reported window (full 2014-2026, 2019+, and MDD): its
    trailing-SR budgets chase regimes, and its SR floor (0.30) kept funding
    a sleeve (BND) through six years of negative realized Sharpe at 15-25%
    of the book (~-20pp cumulative contribution). The classic 1/N result —
    estimation error eats the theoretical gains of optimized weights —
    replicates here. Caveat, stated plainly: the switch was decided after
    seeing that full-sample comparison (one structural choice, same class
    as v3.1's vol-target removal); the a-priori case for 1/N is the
    justification, the comparison is the evidence it wasn't harmful.

Investability (v4): the pre-2024 crypto sleeve history is spot BTC/ETH — a
    stream NO ETF-mandate investor could hold (the only listed vehicle was
    the Grayscale trusts, whose premium chaos the original review rightly
    rejected). Headline metrics therefore allocate to CRY only from IBIT's
    listing. A reference variant allocating to the spot-proxy crypto
    history from 2014 is published in the metrics under
    `reference_spot_proxy_crypto`, clearly labeled NOT INVESTABLE pre-2024.

Overlays (all strictly implementable: the multiplier applied to the return
realized over open[t-1]->open[t] is a function of blend returns through
t-2, i.e. decidable at close[t-2] and traded at open[t-1]):
    - No EWMA vol target (since v3.1: pure drag under the no-margin cap).
    - No drawdown throttle (the historical formula was inert due to a sign
      bug; a corrected throttle was researched and rejected on out-of-sample
      evidence — see apply_overlay and RESEARCH_LOG_V3PLUS.md).
    - Vol-regime gate: halve exposure when 60d vol exceeds its trailing-252d
      99th percentile. NaN warm-up now passes (gate=1.0), matching the live
      implementation — the v3 backtest halved exposure for the first ~118
      days of 2014 because NaN<=NaN evaluates False.
    - 10 bps TC on |change in total multiplier|.

Gross exposure: every sleeve is internally gross <= 1.0 in v4 (VANGUARD's
unfinanced 1.5x internal gross was removed), so the blend's booked notional
is exactly 100% and the live layer's no-margin cap is an assertion rather
than an active constraint. v3 booked a mean 104.7% / max 113.9% notional
while claiming "gross never exceeds 100%".

Honest headline (v4, investable universe, net of costs — exact values in
phoenix_production_metrics.json, regenerated by main()):
    materially below v3.1's advertised SR 1.24 / CAGR 25.9%, which leaned
    on unfinanced sleeve margin, a non-investable pre-2024 crypto stream,
    and a warm-up gate artifact — see alt/PHOENIX_V4_REVIEW.md.
The originally advertised Sharpe 2.34 / "5 uncorrelated sleeves" was an
artifact of misaligned return dating, in-sample ML output and Grayscale
premium economics — documented in alt/PHOENIX_REVIEW.md.
"""
from __future__ import annotations
import json
from pathlib import Path
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "data/results"

BLEND_START = "2014-01-02"   # kept from v3 for series comparability
IS_END = "2018-12-31"        # reporting split only
OOS_START = "2019-01-02"

# v4 allocator: equal weight over active sleeves. Activation dates are fixed
# ex ante (no estimation): IBIT's listing day for CRY (first investable spot
# crypto ETF), blend start for everything else.
ALLOCATOR = "equal_active"   # "equal_active" (v4) | "walk_forward" (v3, reference)
SLEEVE_ACTIVATION = {"CRY": pd.Timestamp("2024-01-11")}

# Sleeve registry: tag -> (csv, column)
SLEEVES = {
    "VAN": ("vanguard_returns.csv", "net_ret"),
    "ORI": ("orion_returns.csv", "orion"),
    "HEL": ("helios_returns.csv", "ret"),
    "CRY": ("crypto_returns.csv", "ret"),
    "REV": ("reversal_returns.csv", "ret"),
    "TOM": ("tom_returns.csv", "ret"),
    "BND": ("bondtrend_returns.csv", "ret"),
}

# Allocator parameters
FIT_YEARS = 4
SR_FLOOR = 0.30
MIN_ACTIVE_VOL = 0.05
W_CAP = 0.35

# Overlay parameters.
# TARGET_VOL = None disables the EWMA vol target (v3.1): under the hard
# no-margin cap a vol target can only REDUCE exposure (the blend's raw vol
# ~20% sits above any sub-20% target most of the time), so it forfeited
# ~5pts of CAGR and ~0.06 Sharpe on the full walk-forward window while
# improving MDD by only ~1pt. The tail overlay (vol gate)
# remain. The full frontier is documented in PHOENIX_V3.md §1b; set a float
# (e.g. 0.18) to restore the vol-targeted profile.
TARGET_VOL = None
EWMA_LAMBDA = 0.94
VOL_CAP = 1.0            # max 100% gross — NO portfolio-level margin
VOL_FLOOR = 0.25
DD_FLOOR = -0.10
DD_WIN = 252
GATE_VOL_WIN = 60
GATE_PCT = 0.99
GATE_LOOKBACK = 252
TC_BPS_PER_LEV_CHG = 10.0


def load_sleeve_returns() -> pd.DataFrame:
    frames = {}
    for tag, (csv, col) in SLEEVES.items():
        df = pd.read_csv(R / csv, parse_dates=["Date"] if tag != "VAN" else [0])
        dc = "Date" if "Date" in df.columns else df.columns[0]
        frames[tag] = df.set_index(dc)[col]
    out = pd.concat(frames, axis=1)
    return out.fillna(0.0)


def _sharpe(r: pd.Series) -> float:
    r = r.dropna()
    if len(r) < 20 or r.std() == 0:
        return 0.0
    return float(r.mean() / r.std() * np.sqrt(252))


def _budget_erc(cov: pd.DataFrame, budgets: pd.Series, iters: int = 500) -> pd.Series:
    w = pd.Series(1.0 / len(cov), index=cov.index)
    b = budgets.reindex(cov.index).clip(lower=1e-6)
    for _ in range(iters):
        rc = w.values * (cov.values @ w.values)
        ratio = (b.values / b.sum()) / np.maximum(rc / max(rc.sum(), 1e-18), 1e-12)
        w = pd.Series(np.clip(w.values * ratio ** 0.3, 1e-6, None), index=cov.index)
        w = w / w.sum()
    return w


def compute_year_weights(sleeve_df: pd.DataFrame, year: int) -> pd.Series:
    """Walk-forward weights for calendar `year`, fit on the trailing
    FIT_YEARS window ending Dec-31 of year-1. Uses only data available
    before the year begins."""
    end = pd.Timestamp(f"{year - 1}-12-31")
    start = end - pd.DateOffset(years=FIT_YEARS)
    win = sleeve_df.loc[start:end]
    w = pd.Series(0.0, index=sleeve_df.columns)
    active = [c for c in win.columns
              if win[c].std() * np.sqrt(252) >= MIN_ACTIVE_VOL]
    if not active:
        return w
    srs = {k: _sharpe(win[k]) for k in active}
    corr = win[active].corr()
    rho_bar = (corr.sum(axis=1) - 1) / max(len(corr) - 1, 1)
    budgets = pd.Series({k: max(srs[k], SR_FLOOR) * max(1 - rho_bar[k], 0.05)
                         for k in active})
    wa = _budget_erc(win[active].cov(), budgets)
    # cap + redistribute. NOTE: no renormalization after capping — the old
    # `wa / wa.sum()` re-inflated capped weights past W_CAP whenever
    # n_active*W_CAP < 1 (e.g. 2 active sleeves -> 0.50/0.50 despite the
    # 0.35 cap). If the cap is infeasible under sum-to-1, the residual
    # stays uninvested (BIL at the live layer) rather than violating it.
    wa = wa / wa.sum()
    for _ in range(20):
        over = wa > W_CAP
        if not over.any():
            break
        excess = float((wa[over] - W_CAP).sum())
        wa[over] = W_CAP
        under = wa[~over]
        if excess <= 1e-12 or under.sum() <= 0:
            break
        room = (W_CAP - wa[~over]).clip(lower=0.0)
        add = (excess * wa[~over] / under.sum()).clip(upper=room)
        wa[~over] = wa[~over] + add
    w[active] = wa.values
    return w


def build_equal_active_weight_frame(sleeve_df: pd.DataFrame) -> pd.DataFrame:
    """v4 allocator: 1/n over sleeves whose fixed activation date has passed.

    Zero estimated parameters. Weight changes happen only on activation
    dates known ex ante, so live and backtest weights are identical by
    construction and there is no fitting window to leak."""
    W = pd.DataFrame(0.0, index=sleeve_df.index, columns=sleeve_df.columns)
    start = pd.Timestamp(BLEND_START)
    for c in sleeve_df.columns:
        act = max(start, SLEEVE_ACTIVATION.get(c, start))
        W.loc[W.index >= act, c] = 1.0
    W = W.div(W.sum(axis=1).replace(0.0, np.nan), axis=0).fillna(0.0)
    return W.loc[BLEND_START:]


def build_wf_weight_frame(sleeve_df: pd.DataFrame) -> pd.DataFrame:
    years = sorted(set(sleeve_df.loc[BLEND_START:].index.year))
    W = pd.DataFrame(0.0, index=sleeve_df.index, columns=sleeve_df.columns)
    for y in years:
        w = compute_year_weights(sleeve_df, y)
        W.loc[str(y)] = w.values
    return W.loc[BLEND_START:]


def build_weight_frame(sleeve_df: pd.DataFrame) -> pd.DataFrame:
    """Weight frame under the ACTIVE allocator (single source of truth for
    production, factsheet, audit and live layers)."""
    if ALLOCATOR == "equal_active":
        return build_equal_active_weight_frame(sleeve_df)
    return build_wf_weight_frame(sleeve_df)


def current_blend_weights() -> dict:
    """Weights in force right now (for the live signal layer)."""
    sleeve_df = load_sleeve_returns()
    if ALLOCATOR == "equal_active":
        w = build_equal_active_weight_frame(sleeve_df).iloc[-1]
    else:
        w = compute_year_weights(sleeve_df, int(sleeve_df.index.max().year))
    return {k: float(v) for k, v in w.items()}


def apply_overlay(raw: pd.Series,
                  target_vol: float | None = TARGET_VOL) -> tuple[pd.Series, pd.DataFrame]:
    """Optional EWMA vol target + DD throttle + vol gate, all applied with an
    effective 2-day shift so every multiplier is decidable before the fill
    that opens the return window it scales."""
    if target_vol is None:
        vol_mult = pd.Series(1.0, index=raw.index)
    else:
        ew_var = raw.pow(2).ewm(alpha=1 - EWMA_LAMBDA).mean()
        ew_vol = (ew_var * 252) ** 0.5
        vol_mult = (target_vol / ew_vol).clip(VOL_FLOOR, VOL_CAP)

    scaled = raw * vol_mult.shift(2).fillna(1.0)
    # NOTE — no drawdown throttle. The historical `(1 + dd/DD_FLOOR).clip(0,1)`
    # formula (here and in the original PHOENIX) had a sign error that made it
    # exactly 1.0 on every date — it never throttled anything. A corrected
    # deadband throttle (-5% -> -15%) was researched: it looked strong on
    # 2014-2018 (SR 1.46 -> 1.65) but REDUCED full-period and 2019+ results
    # (it de-risks into V-shaped recoveries like 2020/2023), so it was
    # rejected rather than shipped. See RESEARCH_LOG_V3PLUS.md iteration 5.
    dd_mult = pd.Series(1.0, index=raw.index)

    sv = scaled.rolling(GATE_VOL_WIN).std()
    sv_thr = sv.rolling(GATE_LOOKBACK, min_periods=60).quantile(GATE_PCT)
    # Gate PASSES while either side is NaN (warm-up): matches the live
    # implementation. The previous `np.where(sv <= sv_thr, 1.0, 0.5)` halved
    # exposure for the whole warm-up window (NaN<=NaN is False) — the first
    # ~118 trading days of 2014 ran at 0.5x on an artifact.
    gate_on = sv.notna() & sv_thr.notna() & (sv > sv_thr)
    gate_mult = pd.Series(np.where(gate_on, 0.5, 1.0), index=raw.index)

    total_dec = vol_mult * dd_mult * gate_mult      # decision-dated (uses raw <= t)
    total_app = total_dec.shift(2).fillna(1.0)      # applied to realization at t
    tc = total_app.diff().abs().fillna(0.0) * (TC_BPS_PER_LEV_CHG / 1e4)
    net = raw * total_app - tc

    state = pd.DataFrame({
        "raw_ret": raw,
        "vol_mult": vol_mult.shift(2).fillna(1.0),
        "dd_mult": dd_mult.shift(2).fillna(1.0),
        "vol_gate_mult": gate_mult.shift(2).fillna(1.0),
        "total_mult": total_app,
        "tc_drag": tc,
        "net_ret": net,
    })
    return net, state


def run_strategy(sleeve_df: pd.DataFrame | None = None,
                 target_vol: float = TARGET_VOL,
                 allocator: str | None = None) -> tuple[pd.Series, pd.DataFrame, pd.DataFrame]:
    if sleeve_df is None:
        sleeve_df = load_sleeve_returns()
    alloc = allocator or ALLOCATOR
    if alloc == "equal_active":
        Wy = build_equal_active_weight_frame(sleeve_df)
    else:
        Wy = build_wf_weight_frame(sleeve_df)
    raw = (sleeve_df.loc[Wy.index] * Wy).sum(axis=1)
    net, state = apply_overlay(raw, target_vol)
    return net, state, Wy


def metrics(r: pd.Series) -> dict:
    r = r.dropna()
    if len(r) == 0:
        return {}
    mu = r.mean() * 252
    sd = r.std() * np.sqrt(252)
    sr = mu / sd if sd > 0 else 0
    c = (1 + r).cumprod()
    dd = (c / c.cummax() - 1).min()
    yrs = len(r) / 252
    cagr = c.iloc[-1] ** (1 / yrs) - 1 if c.iloc[-1] > 0 else -1
    neg = r[r < 0]
    sortino = mu / (neg.std() * np.sqrt(252)) if len(neg) > 0 and neg.std() > 0 else 0
    return {
        "sharpe": round(float(sr), 4),
        "sortino": round(float(sortino), 4),
        "cagr": round(float(cagr), 4),
        "vol": round(float(sd), 4),
        "mdd": round(float(dd), 4),
        "calmar": round(float(cagr / abs(dd)), 4) if dd < 0 else 0,
        "navx": round(float(c.iloc[-1]), 4),
        "n": int(len(r)),
    }


def excess_sharpe(r: pd.Series) -> float:
    """Sharpe with BIL subtracted from the numerator (standard definition)."""
    try:
        bil = pd.read_csv(ROOT / "data/etfs/BIL.csv", parse_dates=["Date"])
        bil = bil.drop_duplicates(subset=["Date"]).set_index("Date").sort_index()
        rf = pd.to_numeric(bil["Open"], errors="coerce").pct_change().reindex(r.index).fillna(0)
        ex = (r - rf).dropna()
        sd = r.dropna().std() * np.sqrt(252)
        return round(float(ex.mean() * 252 / sd), 4) if sd > 0 else 0.0
    except Exception:
        return float("nan")


def main():
    sleeve_df = load_sleeve_returns()
    net, state, Wy = run_strategy(sleeve_df)
    print(f"7-sleeve input: {sleeve_df.index[0].date()} -> {sleeve_df.index[-1].date()}; "
          f"blend starts {net.index[0].date()} (allocator: {ALLOCATOR})")

    w_now = Wy.iloc[-1]
    print("Current weights:", {k: round(float(v), 3) for k, v in w_now.items()})

    m_full = metrics(net)
    m_is = metrics(net.loc[:IS_END])
    m_oos = metrics(net.loc[OOS_START:])
    m_ibit = metrics(net.loc["2024-01-11":])

    print(f"{'window':12s}  {'SR':>5s} {'exSR':>5s} {'CAGR':>6s} {'Vol':>5s} {'MDD':>6s} {'Sortino':>7s} {'NAVx':>6s}")
    for name, m, r in [("FULL(2014+)", m_full, net), ("2014-2018", m_is, net.loc[:IS_END]),
                       ("2019+", m_oos, net.loc[OOS_START:]),
                       ("2024+(7slv)", m_ibit, net.loc["2024-01-11":])]:
        print(f"  {name:10s}  {m['sharpe']:5.2f} {excess_sharpe(r):5.2f} {m['cagr']*100:5.1f}% "
              f"{m['vol']*100:5.1f}% {m['mdd']*100:5.1f}% {m['sortino']:7.2f} {m['navx']:>5.1f}x")
    print(f"  Avg total mult: {state['total_mult'].mean():.3f}   "
          f"TC drag/yr: {state['tc_drag'].sum()/(len(state)/252)*100:.2f}%")

    # Reference variant (research only, NOT the headline): spot-proxy crypto
    # allocated from the blend start. Pre-2024 crypto exposure was NOT
    # investable in an ETF account — published only to show the sensitivity.
    ref_W = Wy.copy()
    ref_W[:] = 0.0
    for c in sleeve_df.columns:
        ref_W.loc[ref_W.index >= pd.Timestamp(BLEND_START), c] = 1.0
    ref_W = ref_W.div(ref_W.sum(axis=1), axis=0)
    ref_raw = (sleeve_df.loc[ref_W.index] * ref_W).sum(axis=1)
    ref_net, _ = apply_overlay(ref_raw)
    m_ref = metrics(ref_net)
    print(f"  [reference, NOT investable pre-2024: spot-proxy crypto from 2014] "
          f"SR {m_ref['sharpe']:.2f} CAGR {m_ref['cagr']*100:.1f}%")

    corr = sleeve_df.loc[BLEND_START:].corr().round(3)

    out = {
        "version": "v4-equal-active",
        "params": {
            "sleeves": {k: v[0] for k, v in SLEEVES.items()},
            "allocator": {"type": ALLOCATOR,
                          "activation": {k: str(v.date()) for k, v in SLEEVE_ACTIVATION.items()},
                          "note": "1/n over active sleeves; zero estimated parameters"},
            "target_vol": TARGET_VOL, "ewma_lambda": EWMA_LAMBDA,
            "vol_cap": VOL_CAP, "vol_floor": VOL_FLOOR,
            "dd_floor": None, "dd_win": None,  # throttle removed (was inert; fix rejected OOS)
            "gate_pct": GATE_PCT, "tc_bps_per_lev_chg": TC_BPS_PER_LEV_CHG,
            "blend_start": BLEND_START,
        },
        "weights_current_year": {k: round(float(v), 4) for k, v in w_now.items()},
        "weights_by_year": {str(y): {k: round(float(v), 4) for k, v in
                                     Wy.loc[str(y)].iloc[0].items()}
                            for y in sorted(set(Wy.index.year))},
        "full": m_full, "is": m_is, "oos": m_oos,
        "since_ibit_2024": m_ibit,
        "excess_sharpe_full": excess_sharpe(net),
        "is_oos_gap": round(abs(m_is["sharpe"] - m_oos["sharpe"]), 4),
        "avg_total_mult": float(state["total_mult"].mean()),
        "reference_spot_proxy_crypto": {
            "warning": "NOT INVESTABLE pre-2024: allocates to spot BTC/ETH "
                       "returns before any spot ETF existed. Research "
                       "reference only — do not quote as performance.",
            **m_ref,
        },
        "correlations": {k: {k2: float(v) for k2, v in row.items()}
                         for k, row in corr.to_dict().items()},
    }
    (R / "phoenix_production_metrics.json").write_text(json.dumps(out, indent=2))
    state.reset_index().rename(columns={"index": "Date"}).to_csv(
        R / "phoenix_production_returns.csv", index=False)
    print("Saved phoenix_production_metrics.json and phoenix_production_returns.csv")


if __name__ == "__main__":
    main()
